[workspace]
[package]
version = "0.1.0"
name = "method"
edition = "2021"

[[bench]]
name = "bench"
harness = false

[build-dependencies]
sp1-helper = "3.4.0"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag = "v3.4.0" }
bincode = "1.3.3"
benchy = "0.1.1"