[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0", features = [
    "std",
    "getrandom",
], tag = "v1.2.0" }

zk_rust_io = { git = "https://github.com/yetanotherco/zkRust.git" }