name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker CPU
        id: meta-cpu
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=main-cpu,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,suffix=-cpu
            type=ref,event=branch,suffix=-cpu
            type=ref,event=pr,suffix=-cpu
            type=semver,pattern={{version}}-cpu
            type=semver,pattern={{major}}.{{minor}}-cpu

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cpu
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-cpu.outputs.tags }}
          labels: ${{ steps.meta-cpu.outputs.labels }}
          cache-from: type=gha,scope=cpu
          cache-to: type=gha,mode=max,scope=cpu

  build-gpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker GPU
        id: meta-gpu
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=main-gpu,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha,suffix=-gpu
            type=ref,event=branch,suffix=-gpu
            type=ref,event=pr,suffix=-gpu
            type=semver,pattern={{version}}-gpu
            type=semver,pattern={{major}}.{{minor}}-gpu

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.gpu
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-gpu.outputs.tags }}
          labels: ${{ steps.meta-gpu.outputs.labels }}
          cache-from: type=gha,scope=gpu
          cache-to: type=gha,mode=max,scope=gpu 